-- Asset Deployer System for rcore_police (Server-side only)
-- Handles deploying items/images into third-party resources (inventories, etc.)
-- Usage: /policesetup <resource> [specific_deploy_name]

if not IsDuplicityVersion() then
    return
end

-----------------------------------------------------------
-- Watermark constants (injected into deployed files)
-----------------------------------------------------------

ASSET_DEPLOYER_WATERMARK_PREFIX = string.format("-- This part is generated by sv-deployer.lua from %s", GetCurrentResourceName())
ASSET_DEPLOYER_WATERMARK_SUFFIX = "-- Do not edit this part manually unless you know what you are doing"

-----------------------------------------------------------
-- File Content Manipulation Helpers
-----------------------------------------------------------

--- Append content after the base string (joins with newlines)
--- @param base string The base content
--- @param ... string Content lines to append
--- @return string Combined content
function append(base, ...)
    return base .. table.concat({...}, "\n")
end

--- Load a file from a resource
--- @param resourceName string The resource to load from
--- @param filePath string The file path within the resource
--- @return string|nil File content
function loadFile(resourceName, filePath)
    return LoadResourceFile(resourceName, filePath)
end

--- Append content after "QBShared.Items = {" pattern
--- @param fileContent string The file content to modify
--- @param insertContent string The content to insert
--- @return string Modified file content
function appendQB(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("QBShared.Items = {", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

--- Append content after "['jailbeds'] = {" pattern
function appendQBHospitalBeds(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("%['jailbeds'%] = {", function(match)
        return match .. "\n" .. insertContent .. ",\n"
    end)
end

--- Append content after "eat = {" pattern
function appendQBConsumablesEat(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("eat = {", function(match)
        return match .. "\n" .. insertContent .. ",\n"
    end)
end

--- Append content after "(ContactData.number)" pattern
function appendQBPhoneTarget(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("%(ContactData%.number%)", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

--- Append content after "(playerId, time)" pattern
function appendQBJailEvent(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("%(playerId, time%)", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

--- Remove QBCore jail command block
function appendQBJailCommand(fileContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("QBCore.Commands.Add%('jail'.-end%)", "")
end

--- Remove QBCore unjail command block
function appendQBUnjailCommand(fileContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("QBCore.Commands.Add%('unjail'.-end%)", "")
end

--- Append content after "drink = {" pattern
function appendQBConsumablesDrink(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("drink = {", function(match)
        return match .. "\n" .. insertContent .. ",\n"
    end)
end

--- Append content after "return {" pattern
function appendAfterReturn(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("return {", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

--- Append content after "BasketballHoops = {" pattern
function appendBasketBallHoops(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("BasketballHoops = {", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

--- Append content after "Config.Items = {" pattern (ESX basic needs)
function appendESXBasicNeedsAfterItems(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("Config.Items = {", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

--- Append content after "return {" (QB door lock)
function appendQBDoorLock(fileContent, insertContent)
    fileContent = fileContent:strtrim()
    return fileContent:gsub("return {", function(match)
        return match .. "\n" .. insertContent .. "\n"
    end)
end

-----------------------------------------------------------
-- Core Deploy Resolution
-----------------------------------------------------------

--- Execute all deploy tasks for a resource
--- @param resourceName string The target resource name
--- @param deployTasks table Map of deploy task names to task definitions
--- @return boolean Whether all deploys succeeded
function resolveDeploy(resourceName, deployTasks)
    if not isResourceLoaded(resourceName) then
        afprint("^1[%s]^7 Resource is not loaded.", Levels.ERROR, resourceName)
        return
    end

    afprint("^3[%s]^7 Deploying resource...", Levels.LOAD, resourceName)

    for taskName, task in pairs(deployTasks) do
        afprint("^3[%s:%s]^7 Processing...", Levels.LOAD, resourceName, taskName)

        if task.type == "file" then
            -- Load file, run callback to modify content, save back
            local fileContent = loadFile(resourceName, task.path)
            local result = task.callback(fileContent, task.callbackData)

            if result then
                SaveResourceFile(resourceName, task.path, result, -1)
                afprint("^2[%s:%s]^7 Successfully saved to %s.", Levels.INFO, resourceName, taskName, task.path)
            else
                afprint("^1[%s:%s]^7 Deploy was not successful.", Levels.ERROR, resourceName, taskName)
            end

        elseif task.type == "basic" then
            -- Simple callback execution
            local success, err = task.callback(task.callbackData)
            if not success then
                afprint("^1[%s:%s]^7 Deploy was not successful: %s", Levels.ERROR, resourceName, taskName, err)
            end

        elseif task.type == "copy-files" then
            -- Copy files from this resource to the target resource
            local sourcePath = task.source
            local targetPath = task.target
            local files = task.callback(task.callbackData)
            local ourResourcePath = GetResourcePath(GetCurrentResourceName())
            local targetResourcePath = GetResourcePath(resourceName)

            for _, fileName in ipairs(files) do
                local sourceFilePath = string.format("%s/%s/%s", ourResourcePath, sourcePath, fileName)
                local sourceFile = io.open(sourceFilePath, "rb")

                if sourceFile == nil then
                    afprint("^1[%s:%s]^7 Source file %s/%s does not exist in resource %s.", Levels.ERROR, resourceName, taskName, sourcePath, fileName, GetCurrentResourceName())
                else
                    local content = sourceFile:read("*a")
                    sourceFile:close()

                    local targetFilePath = string.format("%s/%s/%s", targetResourcePath, targetPath, fileName)
                    local targetFile = io.open(targetFilePath, "wb")

                    if targetFile == nil then
                        afprint("^1[%s:%s]^7 Target file %s/%s does not exist in resource %s.", Levels.ERROR, resourceName, taskName, targetPath, fileName, resourceName)
                    else
                        targetFile:write(content)
                        targetFile:close()
                        afprint("^2[%s:%s]^7 Successfully copied %s from %s to %s.", Levels.INFO, resourceName, taskName, fileName,
                            string.format("%s/%s/", GetCurrentResourceName(), sourcePath),
                            string.format("%s/%s/", resourceName, targetPath))
                    end
                end
            end
        end

        afprint("^2[%s:%s]^7 Successfully processed.", Levels.INFO, resourceName, taskName)
    end

    afprint("^2[%s]^7 Successfully deployed resource.", Levels.INFO, resourceName)
    return true
end

-----------------------------------------------------------
-- Deployer Factory (creates a deployer instance)
-----------------------------------------------------------

--- Create a new Deployer instance with deploy management, KVP caching, and commands
--- @return table Deployer instance
function createDeployer()
    local self = {}
    self.deploys = {}
    self.deploysCache = {}
    self.command = nil
    self.resetDeployCommand = nil
    self.saveDeployInCache = false

    --- Register a file-based deploy (load file, modify, save)
    --- @param deployName string Unique deploy task name
    --- @param resourceName string Target resource
    --- @param filePath string Path to file within the target resource
    --- @param callback function Function(fileContent, callbackData) => modifiedContent
    --- @param callbackData any|nil Data passed to callback
    function self:registerFileDeploy(deployName, resourceName, filePath, callback, callbackData)
        if not self.deploys[resourceName] then
            self.deploys[resourceName] = {}
        end
        self.deploys[resourceName][deployName] = {
            type = "file",
            path = filePath,
            callback = callback,
            callbackData = callbackData or {}
        }
    end

    --- Register a basic deploy (just runs a callback)
    --- @param deployName string Unique deploy task name
    --- @param resourceName string Target resource
    --- @param callback function Function(callbackData) => success, error
    --- @param callbackData any|nil Data passed to callback
    function self:registerDeploy(deployName, resourceName, callback, callbackData)
        if not self.deploys[resourceName] then
            self.deploys[resourceName] = {}
        end
        self.deploys[resourceName][deployName] = {
            type = "basic",
            callback = callback,
            callbackData = callbackData or {}
        }
    end

    --- Register a copy-files deploy (copies files between resources)
    --- @param deployName string Unique deploy task name
    --- @param resourceName string Target resource
    --- @param sourcePath string Source directory in this resource
    --- @param targetPath string Target directory in the target resource
    --- @param callback function Function(callbackData) => table of filenames
    --- @param callbackData any|nil Data passed to callback
    function self:registerCopyFilesDeploy(deployName, resourceName, sourcePath, targetPath, callback, callbackData)
        if not self.deploys[resourceName] then
            self.deploys[resourceName] = {}
        end
        self.deploys[resourceName][deployName] = {
            type = "copy-files",
            source = sourcePath,
            target = targetPath,
            callback = callback,
            callbackData = callbackData or {}
        }
    end

    --- Deploy a specific task for a resource
    function self:deployResourceSpecific(resourceName, deployName)
        if self.saveDeployInCache then
            if self:getDeployStateForResource(resourceName) then
                return afprint("^1[%s]^7 Resource is already deployed.", Levels.ERROR, resourceName)
            end
        end

        return resolveDeploy(resourceName, { [deployName] = self.deploys[resourceName][deployName] })
    end

    --- Deploy all tasks for a resource
    function self:deployResource(resourceName)
        if self.saveDeployInCache then
            if self:getDeployStateForResource(resourceName) then
                return afprint("^1[%s]^7 Resource is already deployed.", Levels.ERROR, resourceName)
            end
        end

        return resolveDeploy(resourceName, self.deploys[resourceName])
    end

    --- Get KVP cache key prefix for a resource
    function self:getDeployCacheNamePrefix(resourceName)
        if resourceName then
            return string.format("%s_%s_%s", GetCurrentResourceName(), "deployer", resourceName)
        end
        return nil
    end

    --- Check if a resource has been deployed (from KVP cache)
    function self:getDeployStateForResource(resourceName)
        local deployed = false
        if resourceName then
            local kvpKey = self:getDeployCacheNamePrefix(resourceName)
            if GetResourceKvpInt(kvpKey) == 1 then
                deployed = true
            end
        end
        return deployed
    end

    --- Set deploy state in KVP cache
    function self:setDeployStateIntoCache(resourceName, state)
        local kvpKey = self:getDeployCacheNamePrefix(resourceName)
        if kvpKey then
            SetResourceKvpInt(kvpKey, state)
        end

        if state == 1 then
            afprint("Resource ^3%s^7 deploy was successfully cached into KVP.", Levels.INFO, resourceName)
        elseif state == 0 then
            afprint("Resource ^3%s^7 deploy was succesfully restarted, could be deployed again via command: (/%s %s)", Levels.LOAD, resourceName, self.command, resourceName)
        end
    end

    --- Delete KVP entry for a resource
    function self:deleteKvpByReourceName(resourceName)
        local kvpKey = self:getDeployCacheNamePrefix(resourceName)
        if kvpKey then
            SetResourceKvpInt(kvpKey, 0)
        end
    end

    --- Get and display the deploy cache status
    function self:getDeployCache()
        local p = promise.new()

        if next(self.deploys) then
            local total = table.len(self.deploys)
            local count = 0

            for resourceName, _ in pairs(self.deploys) do
                count = count + 1

                if resourceName then
                    local deployed = self:getDeployStateForResource(resourceName)
                    if deployed then
                        self.deploysCache[resourceName] = {
                            state = deployed,
                            kvpKey = self:getDeployCacheNamePrefix(resourceName)
                        }
                    end
                end

                if total <= count then
                    p:resolve(true)
                end
            end
        else
            p:resolve(true)
        end

        Citizen.Await(p)

        if self.deploysCache and next(self.deploysCache) then
            afprint("Showing current cached resources into KVP storage!", Levels.LOAD)
            tprint(self.deploysCache)
        else
            afprint("The deployer KVP storage is empty!", Levels.INFO)
        end
    end

    --- Enable/disable KVP caching for deploys
    function self:setSaveDeployInCache(enabled)
        self.saveDeployInCache = enabled
    end

    --- Register the /resetdeploy command
    function self:registerResetDeployCommand(commandName)
        commandName = commandName or "resetdeploy"
        self.resetDeployCommand = commandName

        RegisterCommand(commandName, function(source, args)
            if source ~= 0 then return end

            local resourceName = args[1]
            if resourceName == nil then
                afprint("Usage: /resetdeploy <resource> [name]", Levels.ERROR)
                return
            end

            if not self.deploys[resourceName] then
                afprint("Resource %s is not registered yet.", Levels.ERROR, resourceName)
                return
            end

            if not self:getDeployStateForResource(resourceName) then
                afprint("Resource %s is not stored in KVP storage!", Levels.ERROR, resourceName)
                return
            end

            self:setDeployStateIntoCache(resourceName, 0)
        end)
    end

    --- Register the main /policesetup deploy command
    function self:registerDefaultCommand(commandName)
        commandName = commandName or "deploy"
        self.command = commandName
        self.deployState = false

        RegisterCommand(commandName, function(source, args)
            if source ~= 0 then return end

            local resourceName = args[1]
            if resourceName == nil then
                afprint("Usage: /policesetup <resource> [name]", Levels.ERROR)
                return
            end

            -- Check if resource has registered deploys
            if not self.deploys[resourceName] then
                print(string.format(
                    "^3============================================================^7\n" ..
                    "^3[Deployer Information]^7\n" ..
                    "------------------------------------------------------------\n" ..
                    "- Resource: ^5%s^7\n" ..
                    "- This resource is ^3not registered as a deploy^7.\n" ..
                    "- Nothing is wrong - deploys are only used for moving ^2inventory images/items^7 into your supported inventory.\n" ..
                    "- Integrations are handled automatically if the resource is supported in ^5config.lua^7.\n" ..
                    "- See valid deploys listed below. Only those shown\n" ..
                    "  (policesetup: xxx) can be used if needed.\n" ..
                    "------------------------------------------------------------\n" ..
                    "^3============================================================^7\n",
                    resourceName
                ))
                self:suggestDeploys(true)
                return
            end

            -- Check for specific deploy name
            local specificDeploy = args[2]
            if specificDeploy ~= nil then
                if not self.deploys[resourceName][specificDeploy] then
                    print(string.format(
                        "^3============================================================^7\n" ..
                        "^3[Deployer Information]^7\n" ..
                        "------------------------------------------------------------\n" ..
                        "- Resource: ^5%s^7\n" ..
                        "- This deploy task is ^3not registered^7.\n" ..
                        "------------------------------------------------------------\n" ..
                        "^3============================================================^7\n",
                        resourceName
                    ))
                    self:suggestDeploys(true)
                    return
                end

                self.deployState = self:deployResourceSpecific(resourceName, specificDeploy)
                return
            end

            -- Deploy all tasks for the resource
            self.deployState = self:deployResource(resourceName)

            if self.deployState and self.saveDeployInCache then
                self:setDeployStateIntoCache(resourceName, 1)
            end
        end)
    end

    --- Display suggested deploys for loaded resources
    function self:suggestDeploys(showOutput)
        local availableDeploys = {}
        local cachedDeploys = {}

        if not next(self.deploys) then
            afprint("No deploys are registered yet.", Levels.INFO)
            return
        end

        for resourceName, tasks in pairs(self.deploys) do
            if isResourceLoaded(resourceName) then
                availableDeploys[resourceName] = {}
                cachedDeploys[resourceName] = {}

                for taskName, _ in pairs(tasks) do
                    table.insert(availableDeploys[resourceName], taskName)

                    if self.saveDeployInCache then
                        if self:getDeployStateForResource(resourceName) then
                            table.insert(cachedDeploys[resourceName], taskName)
                        end
                    end
                end
            end
        end

        if showOutput then
            for resourceName, tasks in pairs(availableDeploys) do
                local taskList = table.concat(tasks, "^7,^3 ")

                if self.saveDeployInCache then
                    if self:getDeployStateForResource(resourceName) then
                        afprint("Resource ^3%s^7 is already deployed. Deploy reset command ^3%s^7: ^3%s^7 (/%s %s)",
                            Levels.LOAD, resourceName, table.size(cachedDeploys), taskList, self.resetDeployCommand, resourceName)
                    else
                        afprint("Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (/%s %s)",
                            Levels.LOAD, resourceName, table.size(tasks), taskList, self.command, resourceName)
                    end
                else
                    afprint("Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (/%s %s)",
                        Levels.LOAD, resourceName, table.size(tasks), taskList, self.command, resourceName)
                end
            end
        end

        return availableDeploys
    end

    return self
end
